pageInfo:
  title: FaithNotes
  description: A dashboard for all my self-hosted services
appConfig:
  theme: CyberGlow

sections:
  - name: Work
    icon: fas fa-briefcase
    items:
      - title: Gmail
        description: Email
        url: https://mail.google.com
        icon: fas fa-envelope
        target: newtab
      - title: Google Calendar
        description: Calendar
        url: https://calendar.google.com
        icon: fas fa-calendar-alt
        target: newtab

  - name: Islam
    icon: fas fa-briefcase
    items:
      - title: Quran
        description: Read quran daily
        url: https://quran.com/
        icon: fas fa-book-quran
        target: newtab
      - title: Hadith
        description: Ready one hadith daily
        url: Sunnah.com
        icon: fas fa-feather-alt
        target: newtab              
